version: '3.9'

services:
  redis:
    image: redis:latest
    container_name: keepgoing_redis
    ports:
      - "6355:6379"
    volumes:
      - redis-data:/data

  postgres:
    image: postgres:latest
    container_name: keepgoing_postgres
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydatabase
    ports:
      - "5455:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  redis-data:
  postgres-data:
